### ISSUE TITLE
请教一下如何验证 @spec 和 @type 是否标记正确？

### ISSUE THREAD

**Issue by mydearxym** [zven21/mipha#16]
你好 @zven21 

请教一下 Elixir 里面 `@type` `@spec` 和的定义并不影响结果，那么如果在定义时出现错误或者遗漏，比如 Accounts.User  中没有定义 User 的 type, 如何能发现这个错误？
![image](https://user-images.githubusercontent.com/6184465/42769379-9bde1bc0-8954-11e8-8c78-bd8d44d52501.png)

![image](https://user-images.githubusercontent.com/6184465/42769426-b3305c52-8954-11e8-93f9-ec6dc5801e4f.png)

**Comment by zven21** [comment]
错误如下：
```
== Compilation error in file lib/mipha/accounts/user.ex ==
** (CompileError) lib/mipha/accounts/user.ex:166: type t() undefined
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:198: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

不知道是否可以解决你提出的问题。

**Comment by mydearxym** [comment]
你这个反而是特例，比如把 User.t() 写成 Use.t() 或者 UserNotExsit.t(), 编译就不会报错。 可能要借助一些静态分析工具比如 [dialyxir](https://github.com/jeremyjh/dialyxir) 才能达到理想的效果,  似乎 Elixir 的编译器对 `@spec` 的检查比较鸡肋。

**Comment by mydearxym** [comment]
是的，Elixir 社区只能使用 dialyxir 了。
