### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by zven21** [zven21/mipha#27]
- [ ] Docker + distillery
- [ ] Edeliver + distillery

## References

- [edeliver](https://github.com/edeliver/edeliver)
- [distillery](https://github.com/bitwalker/distillery)

**Comment by grufino** [comment]
What are you thinking about having in this container? I think it shouldn't be easy to set up edeliver with docker, as there is nothing about it in the documentation, but I could set up a basic container image, what do you think?

**Comment by zven21** [comment]
@grufino I think two ways at the moment.

* docker + [distillery](https://github.com/bitwalker/distillery)
* edeliver + [distillery](https://github.com/bitwalker/distillery)

**Comment by yuchunc** [comment]
Hey @zven21, 

we had a few talks on deployment in Elixir Taiwan, and one of them was by edeliver maintainer during Ruby X Elixir Conf Taiwan. The general conclusion around edeliver is that edeliver is really hard to debug, it is essentially a bunch of shell scripts. One of our member propose using Ansible to handle build and deployment commands, it is probably the most stable solution. You can find the details in this post: 

https://www.cogini.com/blog/deploying-your-phoenix-app-to-digital-ocean-for-beginners/

Cheers

**Comment by zven21** [comment]
@yuchunc Thank you. :-)
