### ISSUE TITLE
Encounter a server error when I try to update the my account setting

### ISSUE THREAD

**Issue by keonjeo** [zven21/mipha#29]
# Description

## Step
1. Click the [个人资料设置]  button.
2. upload the photo for my avatar and type the some words into the `description` field.
3. Click the [更新资料] button.
  

## Expected Result

Should update successfully here. the avatar should be replace and the description also should be updated.

## Actual Result

Return the message `Internal Server Error` to the browser.

**Comment by zven21** [comment]
get

**Comment by keonjeo** [comment]
Hi @zven21 @teddy-ma  

The description it works, but the `public email` checkbox still doesn't work well as we expect.
Thanks

**Comment by zven21** [comment]
@keonjeo https://github.com/zven21/mipha/pull/35
