### ISSUE TITLE
add test

### ISSUE THREAD

**Issue by zven21** [zven21/mipha#50]
- [ ] add context test
- [ ] add controller test
- [ ] add plug test

**Comment by zhenyuanlau** [comment]
I want to add testing for mipha.

**Comment by zven21** [comment]
@zhenyuanlau 
好啊，Controller 和 Plug 的测试可以考虑使用 [ex_machina](https://github.com/thoughtbot/ex_machina)

**Comment by zhenyuanlau** [comment]
https://github.com/zven21/mipha/pull/52 还没有开始写测试，做了一点优化和错误修正

**Comment by zven21** [comment]
https://github.com/zven21/mipha/pull/57

**Comment by zven21** [comment]
add new test issue https://github.com/zven21/mipha/issues/59
