### ISSUE TITLE
rucaptcha image doesn't show

### ISSUE THREAD

**Issue by libuchao** [zven21/mipha#53]
![ee](https://user-images.githubusercontent.com/1243202/44558859-14fff400-a779-11e8-88f9-9b0d61a193bc.png)

图片偶尔出不来。

PS: https://elixir-mipha.herokuapp.com/topics/14 二维码更新一下吧

**Comment by zven21** [comment]
@libuchao 验证码超时时间设置问题，我来修复一下。

**Comment by zven21** [comment]
https://github.com/zven21/mipha/pull/54

**Comment by libuchao** [comment]
奇怪，https://github.com/zven21/mipha/pull/54 里好像并没有 `timeout` 相关的修改，只是重命名

**Comment by zven21** [comment]
我改的引用组件  `elixir-captcha` 里面的逻辑。
